apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: generic
  address: http://flux-discord-bridge.flux-system.svc.cluster.local:8080/
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord-notifications
  namespace: flux-system
spec:
  summary: "\U0001F3E0 Lab"
  eventMetadata:
    env: production
    cluster: k3s-lab
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
