apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:2Sa088cHiqJcNXlBuSqumt4WcZ+O9GGULg/5W9mIXJ1rtKaQOTUuJhdh2ZlxXDlsYskVZmAZp7+Xc/q3r6uJxE2C27IGK26VIcJNIWBPA7j5AdNlYIdQqLD+RhQXMhtJt3PVMPzN6QzKtwtTB/TsKy/8lMUvDhe3tw==,iv:t0QGG60DQMjfa+23w8BYBz+EGpSeoR7aps+4Jj7M0QQ=,tag:hlYEbGMTPG1x6XzIFXN9Eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cmU5ajdXRWtBUytsd0Ft
            TGNJMnlzYUdCOURhaVE3c3FEeW5WVm5OYkdJCkNCb1ljT0hrekxjb3ZqeFlHRjhV
            b3I2aTcxTEo5UzJGYkhsUnJhNG56MTAKLS0tIGFFa2FKeC9BdGFIcnUwM1MxdnBT
            NWtXb2dGekVJSEU3dk9JUjVjemsyZFEKHPl/ykyr18T7BT/dVoDP0PMUPcrL0Z2c
            vFQRdXVZyyqJCI9QxvZS7NzdGfGgFDVQmTxaqlGTZH5y/bGIawgRUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17jg4h7zmsjf3ydkc9ngtuqersl6g2a2r3l3wmp5hhdrxm4hjr92qch68kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T09:17:33Z"
    mac: ENC[AES256_GCM,data:VYWexyh48HPHGbGSDF0MwV8sq/zueO3guxbMybTeUASdC9/mECHB2+nc96C5UsYgnk9J307tG3DNoOElN1TsZrDAqvZVDyk8F13E5DbgSD03lNciBcJCpr2XPs7pIrsx9fb9Qa9i17YxoHctCbt3r0DceDvecN3Y9W3tEYlXOZk=,iv:Zmnq+TvgjUBYJUdQG4dSgTIyO89wTF5eWUP7/di/bBs=,tag:nZNVJKZhzZx593IMoKuqZw==,type:str]
    version: 3.13.3
