apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:NbYHFL4=,iv:okMssMhRAIlbJDUvL7U1y1tchzHCeNqcbXXRKV0f2Sc=,tag:utnLrfrrCgz3mdXH0bxdEw==,type:str]
    admin-password: ENC[AES256_GCM,data:w2Ei4J0ehsDcjZhcm3GmxVH/stXiNXhlDQZzvw==,iv:c3HBtWqkk92vaZYzW666pHhZ7nvPVMXriwlzW1PFiZg=,tag:U2bMDEdeORjZkoFtotrabw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa2E2VTBQSGFobFZoUnZH
            R2llaHBpZ1BxWGhWek5kejIzQWRUa3ZXTHhNCjUrS2pSMklzQkJUcGJmTGM0VTA1
            ZzFKZ2lPK2RIZDZXVE5YYXRVSEVTYTQKLS0tIHd2TFFnVGpvQndUODlSMnpaQ1RR
            ZFpDa1pSNXN4eDBGOTl6VVJlNHFHancKlwGTQlpuHhTmEPcgAkaQo7hAz7gIomF/
            d3bjaPGidPvNBrdCTTbWX+dcgpCwgHdb2aBKdAnaEWkXqUsBuH3Jmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17jg4h7zmsjf3ydkc9ngtuqersl6g2a2r3l3wmp5hhdrxm4hjr92qch68kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T09:17:33Z"
    mac: ENC[AES256_GCM,data:fniGWeesKBU4JETicfd5INO6JfvEavXOerlIRlS8Va/FeeJOIbegPQPAxC4+xjdwtfX44p3nems8brvvt+CMvuotB354095OTQAc+q82MSn/i9+6BOePUhKteBFakacdk1IkTjpGuVh2hNn3+77YBMqxOd8nShay7uLT1PUCfac=,iv:vZgtJL4pIgYNkO/UeYJ2VxD28QiQVLl+rqmV3NfH5lo=,tag:JshV/cFr2WI1zw+d5v9TFw==,type:str]
    version: 3.13.3
