apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: storage
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:QO911kuaFsNtWA==,iv:/f/QsFJDoYyaOwDuDBT4r3iAnhsk8hw0Z2YrsDA89Rw=,tag:G3uSxxpa4HUVI3GEWYkMkg==,type:str]
    rootPassword: ENC[AES256_GCM,data:IJRs0jdLZkdSpe35/2IUKdFi1EaPyw==,iv:yccxKDrddU/dNb3Cln8vzW79EFjiTNt6jOfpTcJW8ig=,tag:3Qeg6qAvJViAMwywC+tEDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYnRkMmFWRUNScFhaODBN
            ZTgxeHBPSTlrTms2TlNseHFmS1N5cUNhVG5jCjVDODlsbkJ1T2xzZWh3cWlIVkdW
            YnBrRk00b2pJdWtUY1QrZ3dBWndGS28KLS0tIGZ6eWdHblQ2MFY1TUZxdUNKS2to
            NjBlWHZlL1k1NGx2b3djbktIdmt6QTQK2LposaewlLSss72GdNUZf+cuaMs9yxbe
            IZSN+dGlhv+v44oTcj4ZxXDqBbUFsI3Ayd9Ia/TTtVxF3d3chdVW0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17jg4h7zmsjf3ydkc9ngtuqersl6g2a2r3l3wmp5hhdrxm4hjr92qch68kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T09:17:33Z"
    mac: ENC[AES256_GCM,data:k2ibjYfoApCMnx/H1dMluSeKEtU3rSvnzK3gzuqsAVG0f8qRqTzhlznts0mAW9MmesDo0fkdbCmvvP3K2QSmf2U8WWLOd7mnWFoEsqnzWgnbxLiQV0BHrN38pj7orG5ZrSzPdALzr60KcgrKPT/lO/LCKkLAvwnEOcsxIYISQ3c=,iv:BsYS+UoIjvd2xueVczYLhWVM9iRVcCjQxp3nBZVZbew=,tag:bEts9zFcBEohoEtVEcoBTA==,type:str]
    version: 3.13.3
