apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: storage
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:M3rb94Y0289cnA==,iv:0MqlF3Z1thKFq43UACmg2VZmKuA+KFZmDBjH/BUv4pk=,tag:pT9Wbe5/RuupVLSajhUBMQ==,type:str]
    rootPassword: ENC[AES256_GCM,data:R0aFYk0Zh8izX0WnQwr3xQguG2gmATDIXQI=,iv:9mNQyuhpeTGwsruQwWxu0hts+AU6nVr1dMusIBZlSNg=,tag:s+1it+HcZY+fCL1f282GTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdktlbExZWmt4RHlCMFVR
            SG1RWlZyNksySlZiZzRKaTNFNzRSd2FBUW5jCmVWS2dhcTlFcS95Q1FhRjdwUnpO
            cTJYSFNpS2RtT3ZDM1Ivc1BOWDh0TVEKLS0tIDNQamZIa1R3a2NFaE4rRG0va3JB
            QnJ2blJiUk83RHpsWS9rcTUxaFJ2MlUKODS0IPU/VzYaqN+ZqvADPbk1Dkmn9Abb
            qQgZIE+ZruvOKLIEtXGPkVxVqzhMXwcKAebxC98tBMayACRkIYXW7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17jg4h7zmsjf3ydkc9ngtuqersl6g2a2r3l3wmp5hhdrxm4hjr92qch68kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T10:16:19Z"
    mac: ENC[AES256_GCM,data:dmLiHCqIOMMzGM5EplQEC0TaSYC77HVkkq+zfeCE65rkiKVSIouW4rmTxYHGoE4mPYrOJhJFg1P7mUlStGtVkOtkN5jw8lY50K/RflTv4Q/5lmhdrDkzC6MiEjFvnLm7izqakO3Ct4c8X0oxMLJMuE0gyxHe5gMVaa0BUQ5XSPw=,iv:G/e7OdaeVbKwbLSn+oXSQUsScsN6OTeTTk+/+q+REnQ=,tag:7miKIXmq0iBN7zmqEnP1tQ==,type:str]
    version: 3.13.3
