apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: storage
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:ZWHAU4Mr1Xr5kw==,iv:RuBtgOWrM4SKQCtQjKstCaFr+7K6KNn6TGZOmofWxZ0=,tag:gyagGTmU7Wzuq0k6ZScHXw==,type:str]
    rootPassword: ENC[AES256_GCM,data:NSPRxfaSMtHMVRWcN1QPqaj7Lj9P1f6nong=,iv:LWNIkzM5IL0ngO963tUIwqh/HzdtPIUuJOy5oxbtHwA=,tag:utqNXuW6ZDIM/HHRTyTzWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQTk2ZloyWDJQS2wreEE1
            SkdtQmhlQ1JqWkNxSGk2L3ZzZFFjajFnS1NBCjUvUUlkTkJDc0lhQXNVNFhOUWE1
            R1A5MVAwdThGandRenhUQnZxV2I1YTQKLS0tIElFdnkrKzFNUTVNY1N6RWY3VnBy
            aTgvd2RXc2hjandrTFllSkdlR0pRZXMKDdICP00CcnL0gJDHUcPPhbqhOHe/myG3
            dP5e23QunakK4PweFOHWlovZe9zjcFfCAQ8kiHEfdvrP//QnMYxKGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17jg4h7zmsjf3ydkc9ngtuqersl6g2a2r3l3wmp5hhdrxm4hjr92qch68kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T10:17:26Z"
    mac: ENC[AES256_GCM,data:6ISGhWMW0BDZWJvGV9rfwiOuxEgYXZaqubM0Liimdsq2EKkstyYnMGOKwHcHAsZJBCvl03aUY5Pjox1VG9LBTCiOyUBKKG77jPxTfoageq8cyNNxyox0ZFQIpv0pNtqXfPgSBkrxk9Y2QKye7Bn9+GCjJ4fXmJioSqIOXAC1+Fs=,iv:GVorR50Q7mHFDZlp3BBBXdVXczM6yOp+/EdsYcX2DNw=,tag:Z8H9AYqIuO5Bdk5M6O+E9w==,type:str]
    version: 3.13.3
