apiVersion: v1
kind: Secret
metadata:
    name: pg-lab-app
    namespace: lab-infra
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:iG8m,iv:0ru+8LrllTW/JAjt8PYBRe9vAKdQltPjNVB4jBOgOYg=,tag:jS1eimaGiqxqeeuGxpmjUw==,type:str]
    password: ENC[AES256_GCM,data:tOSWqKOYoPogZfbGyq6Ey0mVWJtkj7nQ30cWnQGCRU/A5R0LB7qmu7Qsx7QaVD5VyH0ZYdIqANvPJ5ENboqDpg==,iv:+Sn946zEwaDqZ/112PeKJjJQW0fa/CJRXNi73/qAoWg=,tag:h9/XqP8oTTzsbFFkdVLQEg==,type:str]
    dbname: ENC[AES256_GCM,data:Ra1s,iv:lmAXBbuwI+CprLxuuw6ocrjkzBWOC8WXmIYkrBZaJzg=,tag:kdWn7K+5GCt2iwuWmesMgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YUFLYmpmblZNQU05cERB
            VjNZVFZ6UFRpdjlEUnN1UDdXNmU1bmczTFVFCmd3cUkydDdFSnpRRjRJd0Yxdnc2
            eUNpbC9odzg2aUIwQTY5eFVkU0hERjAKLS0tIHZETzVOeDl1d0x1dkR6MVA0eUNW
            OGJUeWlRdU5mbzRnNjVmRE4wcmFqMGcK+cU+vlmGRmakf91u4u+a7wrZOdrJ442+
            7JcxcJEJDq7lFimoCg6qXj9HDc7MUmW9IwzBsS4o9TOHceUVcpQcfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17jg4h7zmsjf3ydkc9ngtuqersl6g2a2r3l3wmp5hhdrxm4hjr92qch68kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T09:17:33Z"
    mac: ENC[AES256_GCM,data:0k+7JLEOBlydSG+NhObHfXDgsRDhzC6Ti8D5UJ87CWeHJtH2368+Ar0nx73WkgWc1er1WF3O5XFRE8deBGtzawsAmOVCDy0Q11ycXgqdGPPQVURUTqgt3HECQCaNAfarNYxzHjahF69nQbZ7+uB2DUv7VguiB4nskqTUq9u4CGw=,iv:NiPISfPPYViBs9HhzC2sgE1aWFP8/pzUc58cLvbMXdc=,tag:3m//bDLDe4ReuMasgjYxow==,type:str]
    version: 3.13.3
