apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:BTZny7C8EG5uDE7rV4k3spQ=,iv:ir/MudHrnp0jUF54KDN1BOODDA+kxKiUvjX5DGtb5OI=,tag:5mkw76i0FUWam1zw0pmZQA==,type:str]
    client_secret: ENC[AES256_GCM,data:8PnHXUpJHc4oEnJHIYOphdeD4KrFVLhW57jdtsefRxaSFSsz3Zpvk/Q525V+riYNDaWmNRYFmfZmbyr9aUjd,iv:65vL8Xgi84e9GCdfw/EuNVrkcfstKIlRGNca9I227+w=,tag:krbz4O5mTTO9qnONlMGxDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZlNmR01DbE91bnQ1M0VK
            Nmh3VTV2R3FTT2pZRkt1a2tKbkdWVkNuSVdZCjMybzlsUStLbjY4TXR0WkdwRXNx
            UGdrNzBsNGRCQkR4dUEvZTh4L1dMa2cKLS0tIG82UWxLd2Y2WGR2K2Y3OVUyNmFV
            R0NFOEkxK2FLcWRNeXJ5YmZtQWtaTGsKreE4Fy+WSycD5oG0pliwR2h16/CxJqBS
            U2j8b1GGhYEAl24G2YzhhaW5u9nNIPAZgG8URRtetdaSZFrBTb81Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17jg4h7zmsjf3ydkc9ngtuqersl6g2a2r3l3wmp5hhdrxm4hjr92qch68kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T02:39:53Z"
    mac: ENC[AES256_GCM,data:wZQO+rX/ajB8bwcpKUN05mG5WDzbw36X2P9sksLmEp0ftJdG+6YWIRuLsKE9ODPixoLicUHT3tda4J8ZoH89d32wiQgTTHtvmPR/GOQl3ihCXUofg2WIfngx+ZSEruVq8x6F5vNmCEz48hpieI42kPZCuHWpdulhiLr3wMsMUJI=,iv:JtFOGbglXWnwPi4cq2PmurM13hvJX6BTJEBEG9DBv3s=,tag:SEspGxHyj3vbAnR7C+Aaqw==,type:str]
    version: 3.13.3
