apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-lab
  namespace: lab-infra
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0
  storage:
    size: 10Gi
    storageClass: local-path
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: "2"
  postgresql:
    parameters:
      shared_buffers: 512MB
      max_connections: "200"
  monitoring:
    enablePodMonitor: true
    podMonitorLabels:
      release: kube-prometheus-stack
  bootstrap:
    initdb:
      database: app
      owner: app
      encoding: UTF8
