apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: storage
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:9/ItoYJ9a1Z4gw==,iv:YRN38ieBFzRw0WWUjZtmHQLPQnuFtA0dw35HAWvojm8=,tag:rk+WufdAcAA8UqSvT1hBMg==,type:str]
    rootPassword: ENC[AES256_GCM,data:RaGRfUDLNRU=,iv:9o1YbZE7ju9E42TjLtaZW97azBKG4+qHbD5oRvpKVaM=,tag:BIBq6lpwHGlqHgPInVfSGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMEVGc3h5cnRseWlJR3dR
            VWdxamt1K281bzRSa3M1MFZOUTVGVjBNQUFJCjYzVWx1OUlxY2U3OHIxNUpDdmp6
            WU5NckpxUDhRaFpDazE3R2hVYTFnUlUKLS0tIEFhTzhBOHU3a2dCNERabFZCQStN
            MXBTbDF4dXlhaTZYbHFqZ0x2SGhNY1EK4gA4U1dUy5Axi+/RXKLwwRNpAQia4uMb
            KJU/+5qMweqtuab/PduzotUN3mfnt94jRDphq1/QVOWuu1yXnf6s7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17jg4h7zmsjf3ydkc9ngtuqersl6g2a2r3l3wmp5hhdrxm4hjr92qch68kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T09:13:17Z"
    mac: ENC[AES256_GCM,data:A8VZzt6K126ITCdgWW9OdniQuIQcHxiHVPd4zYabK0DisGJnOAWn96E4vBxGp613IUgreIwfMkzMrOLb+5MyoDctAhaE5/cLhAieWV3whMWC0OzPTUWMFBm37YPHKqP0b5qkvS7GM9jsBH7HHA6cNYvQ60jsWewLgdYcN08gXFs=,iv:2ggdD/JLNsDNg8hTB0BUqWT07vBUNweddWaV6J3c6Qg=,tag:VUozldqD5FtqvXiqCRLFSw==,type:str]
    version: 3.13.3
