apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: lab-infra
data:
  redis.conf: |
    appendonly yes
    appendfsync everysec
    save 900 1
    save 300 10
    maxmemory 256mb
    maxmemory-policy noeviction
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: lab-infra
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:8
        command: ["redis-server"]
        args: ["/usr/local/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: "1"
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        ports:
        - containerPort: 9121
        env:
        - name: REDIS_ADDR
          value: redis://localhost:6379
        resources:
          requests:
            memory: 32Mi
            cpu: 20m
          limits:
            memory: 128Mi
            cpu: 200m
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /usr/local/etc/redis
      volumes:
      - name: config
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: lab-infra
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: redis
  namespace: lab-infra
spec:
  selector:
    matchLabels:
      app: redis
  podMetricsEndpoints:
  - port: exporter
    path: /metrics
    interval: 15s
